steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
      - build
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/docker-repo/appraisers-frontend:$SHORT_SHA'
      - '--build-arg'
      - 'REACT_APP_BACKEND_URL=https://backend-856401495068.us-central1.run.app'
      - '.'

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
      - push
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/docker-repo/appraisers-frontend:$SHORT_SHA'

  # Step 3: Deploy the image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Deploy
    args:
      - 'run'
      - 'deploy'
      - 'appraisers-frontend'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/docker-repo/appraisers-frontend:$SHORT_SHA'
      - '--region'
      - 'us-central1'  # Replace with your desired region if different
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

  # Debug Step: Print Nginx Configuration
  - name: 'gcr.io/cloud-builders/docker'
    id: Debug
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        docker run --rm us-central1-docker.pkg.dev/$PROJECT_ID/docker-repo/appraisers-frontend:$SHORT_SHA cat /etc/nginx/conf.d/default.conf

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/docker-repo/appraisers-frontend:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
