steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'gcr.io/$PROJECT_ID/appraisers-frontend:$COMMIT_SHA'
      - '.'

  # Step 2: Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'gcr.io/$PROJECT_ID/appraisers-frontend:$COMMIT_SHA'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'appraisers-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/appraisers-frontend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'  # Replace with your region
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/appraisers-frontend:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
